"""Layer 23 — CLAUDE.md / AGENTS.md / .cursorrules owned-section management.

graphify-plus writes only between ``<!-- graphify-plus:start -->`` and
``<!-- graphify-plus:end -->``. Everything outside is sacrosanct.

The owned section auto-fills with: top god nodes, active rule violations,
stale-test summary, routing reminder. ``gp daemon claude-md update``
refreshes it. ``--focus <symbol>`` switches to per-task hints.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from .indexes import InMemoryGraph

START_MARKER = "<!-- graphify-plus:start -->"
END_MARKER = "<!-- graphify-plus:end -->"
OWNED_RE = re.compile(re.escape(START_MARKER) + r".*?" + re.escape(END_MARKER), re.DOTALL)


SUPPORTED_FILES = ("CLAUDE.md", "AGENTS.md", ".cursorrules", ".codex/instructions.md")


@dataclass
class ContextSection:
    god_nodes: list[dict[str, Any]]
    rule_violations: list[dict[str, Any]]
    untested_central: list[dict[str, Any]]
    focus: str = ""
    focus_neighbours: list[dict[str, Any]] = None  # type: ignore[assignment]


def build_section(graph: InMemoryGraph, *, focus: str = "") -> ContextSection:
    god = []
    for sid, score in graph.pagerank_top[:5]:
        sym = graph.by_id.get(sid)
        if not sym:
            continue
        god.append(
            {
                "label": sym.get("qualified_name") or sym.get("name") or "",
                "kind": sym.get("kind") or "",
                "source_file": sym.get("path") or "",
                "line_number": int((sym.get("span") or (0, 0))[0]),
                "pagerank": round(score, 6),
            }
        )

    untested = []
    if graph.coverage:
        pr_set = {sid for sid, _ in graph.pagerank_top}
        for sid in pr_set:
            cov = graph.coverage.get(sid)
            if not cov or cov.get("pct", 1.0) > 0.3:
                continue
            sym = graph.by_id.get(sid)
            if sym:
                untested.append(
                    {
                        "label": sym.get("qualified_name") or "",
                        "source_file": sym.get("path") or "",
                        "line_number": int((sym.get("span") or (0, 0))[0]),
                        "coverage_pct": round(cov.get("pct", 0.0) * 100, 1),
                    }
                )

    focus_neigh: list[dict[str, Any]] = []
    if focus:
        from .handlers import _resolve_symbol  # type: ignore[attr-defined]

        sid, _err = _resolve_symbol(graph, {"node": focus})
        if sid:
            for sym in graph.dependents_of(sid)[:5]:
                focus_neigh.append(
                    {
                        "label": sym.get("qualified_name") or "",
                        "source_file": sym.get("path") or "",
                        "line_number": int((sym.get("span") or (0, 0))[0]),
                    }
                )

    return ContextSection(
        god_nodes=god,
        rule_violations=[],  # populated by caller via rules_check
        untested_central=untested,
        focus=focus,
        focus_neighbours=focus_neigh,
    )


def render_section(section: ContextSection, *, repo_name: str = "") -> str:
    lines = [START_MARKER]
    lines.append("<!-- This section is auto-generated by graphify-plus. -->")
    lines.append("<!-- Manual edits inside the markers will be overwritten. -->")
    lines.append("")
    lines.append("## graphify-plus context")
    lines.append("")
    if section.focus:
        lines.append(f"**Current focus**: `{section.focus}`")
        if section.focus_neighbours:
            lines.append("")
            lines.append("Direct dependents:")
            for n in section.focus_neighbours:
                lines.append(f"- {n['label']} `{n['source_file']}:{n['line_number']}`")
        lines.append("")
    if section.god_nodes:
        lines.append("**Top central concepts** (PageRank):")
        for g in section.god_nodes:
            lines.append(f"- {g['label']} [{g['kind']}] `{g['source_file']}:{g['line_number']}`")
        lines.append("")
    if section.untested_central:
        lines.append("**⚠️ Untested central code:**")
        for u in section.untested_central:
            lines.append(
                f"- {u['label']} `{u['source_file']}:{u['line_number']}` ({u['coverage_pct']}%)"
            )
        lines.append("")
    if section.rule_violations:
        lines.append(f"**Active rule violations:** {len(section.rule_violations)}")
        for v in section.rule_violations[:5]:
            lines.append(f"- [{v.get('severity')}] {v.get('rule_id')}: {v.get('message')}")
        lines.append("")
    lines.append("**Routing rule** (graph-vs-grep):")
    lines.append(
        "- Graph for: who_calls, what_depends_on, why_does_this_exist, "
        "whats_central, whats_untested, plan."
    )
    lines.append("- Grep for: literal strings, exact matches, every-occurrence searches.")
    lines.append("")
    lines.append(END_MARKER)
    return "\n".join(lines)


def update_file(path: Path, body: str) -> dict[str, Any]:
    """Write the owned-section body into ``path``, replacing any existing
    block between markers. If markers are missing, appends.
    """
    if path.exists():
        text = path.read_text(encoding="utf-8")
    else:
        text = f"# {path.name}\n\n"
    if OWNED_RE.search(text):
        new_text = OWNED_RE.sub(body, text)
        action = "updated"
    else:
        sep = "" if text.endswith("\n") else "\n"
        new_text = text + sep + "\n" + body + "\n"
        action = "appended"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(new_text, encoding="utf-8")
    return {"action": action, "path": str(path)}


def update_all_known(repo_root: Path, body: str) -> list[dict[str, Any]]:
    """Update every supported context file that already exists. Doesn't
    create new ones unless CLAUDE.md is missing — that's the canonical
    surface, so we always create that.
    """
    out: list[dict[str, Any]] = []
    canonical = repo_root / "CLAUDE.md"
    out.append(update_file(canonical, body))
    for name in SUPPORTED_FILES[1:]:
        p = repo_root / name
        if p.exists():
            out.append(update_file(p, body))
    return out


def strip_owned_section(text: str) -> str:
    return OWNED_RE.sub("", text).rstrip() + "\n"


__all__ = [
    "ContextSection",
    "OWNED_RE",
    "SUPPORTED_FILES",
    "build_section",
    "render_section",
    "strip_owned_section",
    "update_all_known",
    "update_file",
]
