class GraphifyPlus < Formula
  include Language::Python::Virtualenv

  desc "Universal context & execution engine for AI coding agents"
  homepage "https://github.com/ahmadzubair9655/graphify-plus"
  url "https://files.pythonhosted.org/packages/source/g/graphify-plus/graphify-plus-5.1.0.tar.gz"
  sha256 "PLACEHOLDER_SHA256"
  license "MIT"

  depends_on "python@3.12"
  depends_on "tree-sitter"

  resource "networkx" do
    url "https://files.pythonhosted.org/packages/source/n/networkx/networkx-3.0.tar.gz"
    sha256 "PLACEHOLDER"
  end

  # Additional dependency resources are auto-generated by `brew update-python-resources`
  # when the formula is published. This file is the scaffold the maintainer fills in.

  def install
    virtualenv_install_with_resources
  end

  test do
    output = shell_output("#{bin}/gp --help")
    assert_match "Subcommands", output
  end
end
